---

- hosts: dockerhosts
  sudo: false
  vars:
    dns_server: 10.32.0.13
    user: vagrant
  remote_user: "{{ user }}"
  roles:
    - role: base
#    - role: docker

#- hosts: localhost
#  connection: local
#  vars:
#    docker_host: 'tcp://127.0.0.1:2375'
#  roles:
#    - docker_containers